services:
  mysql:
    container_name: bbs-go-mysql
    image: 'mysql:8.0'
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: bbsgo_db
      MYSQL_USER: bbsgo
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - .docker-compose/mysql/data:/var/lib/mysql # 挂载数据件目录；如果非root账号执行，挂载目录必须是登录账号下目录
    restart: always
    healthcheck:
      test: '/usr/bin/mysql --user=bbsgo --password=123456 bbsgo_db --execute "SHOW TABLES;"'
      interval: 3s
      timeout: 300s
      retries: 100
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  bbsgo:
    container_name: bbs-go
    image: mlogclub/bbs-go:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      BBSGO_ENV: prod
    ports:
      - 8082:8082
      - 3000:3000
    restart: on-failure
